### ISSUE TITLE
How to use %recipient.yourvar% template variable in a template ?

### ISSUE THREAD

**Issue by naveenbharadwaj19** [dotronglong/flutter-mailgun#5]
Hey ! 
i've been trying to add the custom data template variable in my template how to do it ? 
i replaced %recipient.yourvar% to %recipient.fourdigitcode% i read the docs but still not clear i want to place a string in my template
**Html code:**

`<td class="pc-xs-fs-30 pc-xs-lh-42 pc-fb-font pc-xs-br-disabled" valign="top" style="padding: 13px 10px 0; letter-spacing: -0.7px; line-height: 46px; font-family: 'Open Sans', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 800; color: #ffffff">
                                          <p>%recipient_email%,</p>
                                          <p>We're excited to have you get started. First, you need to confirm your account.</p>
                                          <p>Your verification code is :</p>
                                          <p>%recipient.fourdigitcode%</p>
                                          <p>If you think we made mistake ignore this email</p>
                                          <p>Cheers,</p>
                                          <p>Team Explore</p>
                                        </td>`

the mail how i'm getting :
![mailgun](https://user-images.githubusercontent.com/63662884/100749607-e6b6f780-340a-11eb-9e3e-c40b8f2605f0.png)
**My goal is to replace %recipient.fourdigitcode% as text like 12345**

**Comment by dotronglong** [comment]
Hi,

Can you try `{{recipient.fourdigitcode}}` instead of `%recipient.fourdigitcode%` in your mailgun template configuration, and in the flutter code you can set template variables to `recipient.fourdigitcode`. Please try and let me know if it works.

**Comment by naveenbharadwaj19** [comment]
@dotronglong Hi, 
Thanks for the reply i haven't tried `{{recipient.fourdigitcode}}` instead i warped with `{{{recipient.fourdigitcode}}} - this one worked`. What's the use of warping the variable in `{{}},{{{}}}` ?

**Comment by dotronglong** [comment]
Hi, it’s rule of mailgun 👍
