### ISSUE TITLE
Do you really need a Flutter dependency?

### ISSUE THREAD

**Issue by hasimyerlikaya** [dotronglong/flutter-mailgun#6]
Hi,
I want to use it in a Shelf api that I wrote with Dart, but I cannot use it due to Flutter dependency.

Is it possible to fix this?

Thank you.

**Comment by dotronglong** [comment]
I am not sure what you are saying, can you give me more information?

**Comment by hasimyerlikaya** [comment]
Mail and the pubspec.yaml file in this package are included in the Flutter dependency.

In fact, Flutter is not required for both packages to work.
If you uninstall Flutter, your packages will also work in Dart console applications.

![image](https://user-images.githubusercontent.com/7986394/103608293-1b4b3100-4f2c-11eb-815d-53b5bf94fe8b.png)

https://raw.githubusercontent.com/dotronglong/flutter-mailgun/master/pubspec.yaml

**Comment by dotronglong** [comment]
Hi, thank you for your information, however, I am not still getting your point. `mail` package provides interface for `flutter-mailgun` to implement. I believe you are getting problems regarding dependencies in your application, hence, I would like to ask if you can provide more relevant information about your application, e.g, which conflict packages prevents you from using this plugin.

**Comment by hasimyerlikaya** [comment]
I used your code embedded, there is no problem for me right now. It was just a recommendation so more people could use it.
Thank you.

![image](https://user-images.githubusercontent.com/7986394/103609608-43885f00-4f2f-11eb-8198-8046f2797507.png)

**Comment by dotronglong** [comment]
Since `mail` is designed for flutter users only, hence, it depends on flutter sdk. I will consider it to be used for dart/web in the future. Thank you for your information.
