### ISSUE TITLE
Updating to null safe version?

### ISSUE THREAD

**Issue by yakou32** [dotronglong/flutter-mailgun#7]
The 0.1.2 version generates this warning: "The library 'package:mailgun/mailgun.dart' is legacy, and should not be imported into a null safe library."

Is it possible to update the package to a null safe version?

Thank you!

**Comment by dotronglong** [comment]
@yakou32 can you give me information about your current flutter environment? Thank you.

**Comment by yakou32** [comment]
I'm using `sdk: ">=2.12.0 <3.0.0"` with `http: 0.13.0-nullsafety.0`

I think it's just a matter of syntax update to maker flutter-mailgun compatible.

This is what I updated so far for the `send()` method, but I'm not confident enough to propose it as a pull request.
```
 {
      String? from,
      List<String> to = const [],
      List<String> cc = const [],
      List<String> bcc = const [],
      List<dynamic> attachments = const [],
      String? subject,
      String? html,
      String? text,
      String? template,
      Map<String, dynamic>? options
}
```
And also
```
SendResponse({required this.status, this.message = ''});
```
I'm not so sure if this is enough for null safety compliance.

**Comment by dotronglong** [comment]
Hi,

What if you try to use `http: ^0.12.1` instead, I try you  are using a higher version of http than the package itself.

**Comment by yakou32** [comment]
I'm now using `http; ^0.13.1` version due to other dependencies null safety requirements.

**Comment by dotronglong** [comment]
I believe `0.13.1` is quite new, and it also requires higher dart sdk, hence, I would suggest you to stay with current `0.12.1` or you will need to find another way, e.g, fork from this repository.

**Comment by crushman1** [comment]
This may not be the best approach but to get mailgun working with the latest version of http, you can override the dependancy in your pubspec.yaml like this : 
`dependency_overrides:
  http: ^0.13.1`

**Comment by crushman1** [comment]
This works any chance this package will migrate to null safety ? because of this one package i have to compile without null safety enabled.
