### ISSUE TITLE
doesnt seem to work on EU zone

### ISSUE THREAD

**Issue by crushman1** [dotronglong/flutter-mailgun#8]
I have everything setup as described. Sending the email via US zone works. Sending it via EU doesn't work. I get the error : 
`
FormatException: Unexpected character (at character 1)
I/flutter (17973): Forbidden
I/flutter (17973): 
`
 I saw online that there was suppose to be another parameter called `host` thats suppose to be set up like this : `host: "api.eu.mailgun.net"` but there is no such parameter for this package.

**Comment by stringgle** [comment]
I believe there was a domain for mailgun. For example
```
import 'package:mailgun/mailgun.dart';


var mailgun = MailgunMailer(domain: "my-mailgun-domain", apiKey: "my-mailgun-api-key");
```

**Comment by crushman1** [comment]
That domain param doesnt purtain to that. It refers to the email domain. For example mg.mydomain.com.

What i am refering to is the server zone u have to select when you first sign up to mailgun. US or EU.

**Comment by crushman1** [comment]
Anyway, i was able to solve it by downloading the package code manually and literally changing the zone url to `api.eu.mailgun.net` which is great because now i can have null safety and dont have to add this extra package to pubspec

**Comment by dotronglong** [comment]
Thank you.
